// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMMUzlbbFJqBeKf8MpSV7A3UGnoSttNyw',
    appId: '1:91415223664:web:2c4dcaa286c2ecfeef03b5',
    messagingSenderId: '91415223664',
    projectId: 'fir-firestoremvvmcrud-26689',
    authDomain: 'fir-firestoremvvmcrud-26689.firebaseapp.com',
    storageBucket: 'fir-firestoremvvmcrud-26689.firebasestorage.app',
    measurementId: 'G-8EVPTFLS92',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEnQinQ3b4CSp1RGdXkYqobzPuuB-pfM4',
    appId: '1:91415223664:android:668b9bcdf6a93f5eef03b5',
    messagingSenderId: '91415223664',
    projectId: 'fir-firestoremvvmcrud-26689',
    storageBucket: 'fir-firestoremvvmcrud-26689.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-mxhu0XKcofAQxDuMfKTFYPiUrSFIzcs',
    appId: '1:91415223664:ios:79bd305395a4e7cbef03b5',
    messagingSenderId: '91415223664',
    projectId: 'fir-firestoremvvmcrud-26689',
    storageBucket: 'fir-firestoremvvmcrud-26689.firebasestorage.app',
    iosBundleId: 'com.example.miniStore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-mxhu0XKcofAQxDuMfKTFYPiUrSFIzcs',
    appId: '1:91415223664:ios:79bd305395a4e7cbef03b5',
    messagingSenderId: '91415223664',
    projectId: 'fir-firestoremvvmcrud-26689',
    storageBucket: 'fir-firestoremvvmcrud-26689.firebasestorage.app',
    iosBundleId: 'com.example.miniStore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAMMUzlbbFJqBeKf8MpSV7A3UGnoSttNyw',
    appId: '1:91415223664:web:996c2319098f4a95ef03b5',
    messagingSenderId: '91415223664',
    projectId: 'fir-firestoremvvmcrud-26689',
    authDomain: 'fir-firestoremvvmcrud-26689.firebaseapp.com',
    storageBucket: 'fir-firestoremvvmcrud-26689.firebasestorage.app',
    measurementId: 'G-JW7CK8GMG5',
  );
}
